### ISSUE TITLE
cv2.structured_light_GrayCodePattern.getProjPixel function lacking arguments?

### ISSUE THREAD

**Issue by SHL4917** [kamino410/procam-calibration#3]
Hi, when running the code, I got the error where the getProjPixel() argument is missing an additional required argument projPix (4th argument). This is at line 144 btw. Thank you!

**Comment by sreenithy** [comment]
Hi, I am facing the same issue as well. Has this been solved @SHL4917 @kamino410

**Comment by kamino410** [comment]
Thank you for your comments and sorry for being late.
But as I checked test code described in the README with the latest libraries, I didn't see that bug.

* Python 3.7.4
* opencv-python 3.4.x / 4.2.0.32
* opencv-contrib-python 3.4.x / 4.2.0.32

I guess that this bug is caused by not arguments of `projPix` but invalid input images; captured graycode pattern is not fine etc. I've not implemented careful error handling there.

Could you check your library version and captured images?

**Comment by sreenithy** [comment]
Thank you @kamino410 for replying, it was an issue with library version mismatch. Fixed it now.

Thank you.
